version: "3"

services:
  web:
    container_name: hazzvite/node-app
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: hazzvite/mongo:latest
    image: mongo
    ports:
      - "27018:27017"





      