version: "3"

services:
  web:
    container_name: node-app
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - mongo
  mongodb:
    container_name: mongo-db
    image: mongo
    ports:
      - "27018:27017"